default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: ubuntu
  password: password

development:
  <<: *default
  database: falaairecife_dev

test:
  <<: *default
  database: falaairecife_test

production:
  <<: *default
  database: falaairecife_prod


